### ISSUE TITLE
`kde-connect` url changed

### ISSUE THREAD

**Issue by BingoKingo** [hybras/homebrew-tap#128]
They have moved to GitLab: https://blogs.kde.org/2024/01/30/farewell-binary-factory-add-craft-jobs-your-apps-kdes-gitlab-now/

https://invent.kde.org/network/kdeconnect-kde/-/artifacts

**Comment by hybras** [comment]
Please open a PR

**Comment by hybras** [comment]
In fact, this fix should be upstreamed: https://invent.kde.org/packaging/homebrew-kde

**Comment by hybras** [comment]
I couldn't figure out stable urls, but kde's homepage had nice nightly download urls
